# Github Link: https://github.com/binalbariya/Deep-Learning/blob/main/Assignment%205/RNN.ipynb

#This is for implementing RNN using keras for Text Generation.

In [35]:
# importing essential libraries
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import LSTM
from keras.utils import np_utils


My input file will be a section of a play from the playwright genius Shakespeare. I will be using a monologue from Othello.

In [36]:
#Firstly formatting the input_file so that it can be well understood by keras

#Read the data, turn it into lower case
data = open("input_file.txt").read().lower()


In [37]:
#This get the set of characters used in the data and sorts them
chars = sorted(list(set(data)))
chars

['\n',
 ' ',
 "'",
 ',',
 '-',
 '.',
 ';',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'y']

In [38]:
#Total number of characters used in the data
totalChars = len(data)
totalChars

1860

In [39]:
#Number of unique chars
numberOfUniqueChars = len(chars)
numberOfUniqueChars

30

create a dictionary of each character so it can be easily represented

In [40]:
#This allows for characters to be represented by numbers
CharsForids = {char:Id for Id, char in enumerate(chars)}
CharsForids

{'\n': 0,
 ' ': 1,
 "'": 2,
 ',': 3,
 '-': 4,
 '.': 5,
 ';': 6,
 'a': 7,
 'b': 8,
 'c': 9,
 'd': 10,
 'e': 11,
 'f': 12,
 'g': 13,
 'h': 14,
 'i': 15,
 'k': 16,
 'l': 17,
 'm': 18,
 'n': 19,
 'o': 20,
 'p': 21,
 'q': 22,
 'r': 23,
 's': 24,
 't': 25,
 'u': 26,
 'v': 27,
 'w': 28,
 'y': 29}

In [41]:
#This is the opposite to the above
idsForChars = {Id:char for Id, char in enumerate(chars)}
idsForChars

{0: '\n',
 1: ' ',
 2: "'",
 3: ',',
 4: '-',
 5: '.',
 6: ';',
 7: 'a',
 8: 'b',
 9: 'c',
 10: 'd',
 11: 'e',
 12: 'f',
 13: 'g',
 14: 'h',
 15: 'i',
 16: 'k',
 17: 'l',
 18: 'm',
 19: 'n',
 20: 'o',
 21: 'p',
 22: 'q',
 23: 'r',
 24: 's',
 25: 't',
 26: 'u',
 27: 'v',
 28: 'w',
 29: 'y'}

In [42]:
#How many timesteps e.g how many characters we want to process in one go
numberOfCharsToLearn = 100

In [43]:
CharsForids["o"]

20

In [44]:
#Input data
charX = []
#Output data
y = []

In [45]:
#Since our timestep sequence represetns a process for every 100 chars we omit
#the first 100 chars so the loop runs a 100 less or there will be index out of
#range
counter = totalChars - numberOfCharsToLearn
#This loops through all the characters in the data skipping the first 100
for i in range(0, counter, 1):
  #This one goes from 0-100 so it gets 100 values starting from 0 and stops
  #just before the 100th value
  theInputChars = data[i:i+numberOfCharsToLearn]
  #With no ':' you start with 0, and so you get the actual 100th value
  #Essentially, the output Chars is the next char in line for those 100 chars in charX
  theOutputChars = data[i + numberOfCharsToLearn]
  #Appends every 100 chars ids as a list into charX
  charX.append([CharsForids[char] for char in theInputChars])
  #For every 100 values there is one y value which is the output
  y.append(CharsForids[theOutputChars])

#To convert data into right format which can be fed to RNN


In [46]:
#Len(charX) represents how many of those time steps we have
#The numberOfCharsToLearn is how many character we process
#Our features are set to 1 because in the output we are only predicting 1 char
X = np.reshape(charX, (len(charX), numberOfCharsToLearn, 1))


In [47]:
#This is done for normalization
X = X/float(numberOfUniqueChars)
#This sets it up for us so we can have a categorical(#feature) output format
y = np_utils.to_categorical(y)
print(y)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


#Building RNN Model

In [48]:
 model = Sequential()


In [49]:
#Since we know the shape of our Data we can input the timestep and feature data
#The number of timestep sequence are dealt with in the fit function
model.add(LSTM(256, input_shape=(X.shape[1], X.shape[2])))
model.add(Dropout(0.2))


In [50]:
#number of features on the output
model.add(Dense(y.shape[1], activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam')
model.fit(X, y, epochs=50, batch_size=128)
model.save_weights("Othello.hdf5")
#model.load_weights("Othello.hdf5")

Epoch 1/50
14/14 [==============================] - 2s 22ms/step - loss: 3.2764
Epoch 2/50
14/14 [==============================] - 0s 21ms/step - loss: 3.0094
Epoch 3/50
14/14 [==============================] - 0s 20ms/step - loss: 2.9824
Epoch 4/50
14/14 [==============================] - 0s 21ms/step - loss: 2.9896
Epoch 5/50
14/14 [==============================] - 0s 20ms/step - loss: 3.0184
Epoch 6/50
14/14 [==============================] - 0s 20ms/step - loss: 3.0109
Epoch 7/50
14/14 [==============================] - 0s 20ms/step - loss: 3.0050
Epoch 8/50
14/14 [==============================] - 0s 20ms/step - loss: 2.9855
Epoch 9/50
14/14 [==============================] - 0s 20ms/step - loss: 2.9962
Epoch 10/50
14/14 [==============================] - 0s 20ms/step - loss: 2.9975
Epoch 11/50
14/14 [==============================] - 0s 20ms/step - loss: 2.9603
Epoch 12/50
14/14 [==============================] - 0s 21ms/step - loss: 2.9644
Epoch 13/50
14/14 [==================

#Code to generate new text

In [57]:
for i in range(500):
  randomVal = np.random.randint(0, len(charX)-1)
  randomStart = charX[randomVal]

  x = np.reshape(randomStart, (1, len(randomStart), 1))
  x = x/float(numberOfUniqueChars)
  pred = model.predict(x)
  index = np.argmax(pred)
  randomStart.append(index)
  randomStart = randomStart[1: len(randomStart)]

#So our newly generated text is:




In [58]:
print("".join([idsForChars[value] for value in randomStart]))

hence;
which ever she could with haste dispatch,
she'd come again, and with a greedy ear
devour up th
